apiVersion: v1
kind: Namespace
metadata:
 name: chaos
---
apiVersion: v1
kind: Pod
metadata:
  name: chaos-dns-enum
  namespace: chaos
  labels:
    chaoskube: dns-enum
spec:
  containers:
  - name: dns-enum
    image: ubuntu
    command: [ "/bin/bash", "-c", "--"]
    args: [ "apt-get update -y && apt-get install curl -y && curl lwmalwaredemo.com && curl metasploit.com"]